server:
  port: ${PORT:8761}
  
---
spring:
  profiles: openshift
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
---
spring:
  profiles: statefulset
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary
  server:
    registry-sync-retry-wait-ms: 500
    eviction-interval-timer-in-ms: 30000
    a-s-g-cache-expiry-timeout-ms: 60000
    peer-eureka-nodes-update-interval-ms: 30000
    renewal-threshold-update-interval-ms: 15000
